### ISSUE TITLE
Hi, some errors with pip install

### ISSUE THREAD

**Issue by Fan123456-c** [staymylove/3DMIT#3]
when I use 'pip install -r requirements.txt ', 
it back:
ERROR: Could not find a version that satisfies the requirement lightllm==2.0.0 (from versions: none)
ERROR: No matching distribution found for lightllm==2.0.0
How can I solve that?

**Comment by staymylove** [comment]
Please notice that this work was done in 2024.01, I think the package lightllm was updated, so it may warn that the 2.0.0 version no matching distribution.
So I think you should pip the lightllm alone for the appropriate verison.

**Comment by Fan123456-c** [comment]
And also:
ERROR: Could not find a version that satisfies the requirement pointnet2 (from versions: none)
ERROR: No matching distribution found for pointnet2

**Comment by Fan123456-c** [comment]
I am confused, when I use 'pip install lightllm', there is no package about lightllm:
ERROR: Could not find a version that satisfies the requirement lightllm (from versions: none)
ERROR: No matching distribution found for lightllm.
when I searched this python package in _https://pypi.org/_, it showed: 
![image](https://github.com/user-attachments/assets/3d33b4dc-3d29-455d-9655-c45e919f7b1d)

**Comment by staymylove** [comment]
you can get the sources here:
https://github.com/charlesq34/pointnet2
https://github.com/ModelTC/lightllm
and you should install by hand

**Comment by Fan123456-c** [comment]
Hi, pointnet2 which from https://github.com/charlesq34/pointnet2 allows me to install TensorFlow? Could you tell me how to install it detailedly? Thank you.
![image](https://github.com/user-attachments/assets/bb483f13-f06e-41b7-9545-7707f9bab95a)

**Comment by staymylove** [comment]
NO, the env does not contain the tensorflow, if you pip install tensorflow, other packages will be changed.
You should manually git clone pointnet and setup.
![image](https://github.com/user-attachments/assets/1a6264ad-c7a6-4e5b-a58a-6e28c0a16f93)

**Comment by Fan123456-c** [comment]
Thank you for your answer. Could you tell me the dataset directory structure in your code when I downloaded two datasets?

**Comment by staymylove** [comment]
You can just download the data and set you own path in the training and eval script.
