### ISSUE TITLE
Hi, epcl_scannet_vit-L-14_256tokens_latest.pth  need  what kind of graphics card，and for how long？

### ISSUE THREAD

**Issue by yun189** [staymylove/3DMIT#4]
and, will you release weight file, please?

**Comment by staymylove** [comment]
This is the link
https://drive.google.com/file/d/177yY53BGMELlVFWlmHYArE0HlCFsCntW/view?usp=sharing

and the best ckpt of 3dmit will be uploaded later

**Comment by yun189** [comment]
thanks for your reply
