### ISSUE TITLE
hi, where is ckpt/zeju_0318_bs_1_onlyvg_vicuna_index/answers-vg/zeju-0318-bs-1-vg-vicuna-index/VG_ScanRefer.jsonl?

### ISSUE THREAD

**Issue by yun189** [staymylove/3DMIT#5]
when run src/vg_eval_script.py, error happened: 
Traceback (most recent call last):
  File "3DMIT/src/vg_eval_script.py", line 15, in <module>
    with open(data,'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: './ckpt/zeju_0318_bs_1_onlyvg_vicuna_index/answers-vg/zeju-0318-bs-1-vg-vicuna-index/VG_ScanRefer.jsonl'
what can i do?

**Comment by yun189** [comment]
when i run src/scripts/3DMIT_3D_Evaluation_7b.sh,
  File "3DMIT/src/inference_3d.py", line 2
    from src.model.3dmit import 3DMITPEFT
                   ^
SyntaxError: invalid decimal literal
Traceback (most recent call last):
  File "3DMIT/src/cal_scanqa_score.py", line 13, in <module>
    from datasets import load_3Deval_dataset
ImportError: cannot import name 'load_3Deval_dataset' from 'datasets' 
so,where is  load_3Deval_dataset?

**Comment by staymylove** [comment]
For you first question, this file is the result after you trained and evaluated the model. And I have shared the link the result in the readme.

**Comment by staymylove** [comment]
For you 2nd question, I have updated the code of dataset initiation.

**Comment by yun189** [comment]
thanks for your reply！thought ckpt do not contain：
VG_ScanRefer.jsonl。which file can replace it？
